# Generated by Django 6.0.5 on 2026-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('covered_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_status', models.CharField(choices=[('CONSTRUCTION', 'En construcción'), ('NEW', 'A estrenar'), ('USED', 'Años de antigüedad')], max_length=20)),
                ('age_years', models.PositiveIntegerField(default=0)),
                ('rooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('toilettes', models.PositiveIntegerField(default=0)),
                ('garages', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
