# Generated by Django 6.0.5 on 2026-05-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
    ]
