# Generated by Django 6.0.5 on 2026-05-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='operation_type',
            field=models.CharField(choices=[('SALE', 'Venta'), ('RENT', 'Alquiler')], default='SALE', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
